---
name: chrony
version: dev
slug: chrony
description: A local NTP (Network Time Protocol) server for cameras etc.
url: https://github.com/nethershaw/addon-chrony
# codenotary: codenotary@frenck.dev
startup: system
arch:
  - aarch64
  - amd64
hassio_api: true
init: false
privileged:
  - SYS_TIME
ports:
  123/udp: 123
  323/udp: 323
ports_description:
  123/udp: NTP; Network Time Protocol
  323/udp: Chrony; client/server command and monitoring
options:
  set_system_clock: true
  ntp_pool: time.example.com
  ntp_server:
    - 198.51.100.123
    - 0.time.example.org
  ntp_peer:
    - 192.0.2.123
    - local.ntp-server.test
  allow:
    - 10.0.1.1/24
  bindcmdaddress:
    - 127.0.0.1
    - ::1
  cmdallow: []
  cmddeny: []
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  set_system_clock: bool
  ntp_pool: str?
  ntp_server:
    - str?
  ntp_peer:
    - str?
  allow:
    - str?
  bindcmdaddress:
    - str?
  cmdallow:
    - str?
  cmddeny:
    - str?
